### PR TITLE
Updating ADB box's atlas namespace

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty lmohanty@redhat.com

### CODE REVIEW

**Comment by bexelbie** [comment]
LGTM

@navidshaikh ?

**Comment by navidshaikh** [comment]
LGTM, it needs rebase to reflect the changes in README.

**Comment by LalatenduMohanty** [comment]
@bexelbie @navidshaikh re-based the patch

**Comment by bexelbie** [comment]
Still LGTM

@navidshaikh ?

**Comment by navidshaikh** [comment]
Yeah, LGTM

**Pull request merged**
